name: Deploy DHIL Symfony Base Image

on:
  push:
    tags:
      - '*'

jobs:
  deploy-base-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build & Push Symfony Base
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        pull: true
        tags: dhilsfu/symfony-base:latest,dhilsfu/symfony-base:${{github.ref_name}}
        cache-from: type=registry,ref=dhilsfu/symfony-base:buildcache
        cache-to: type=registry,ref=dhilsfu/symfony-base:buildcache,mode=max
